lnorby_media_upload_file:
    path: /upload/file
    controller: Lnorby\MediaBundle\Controller\MediaController::uploadFile
    methods: POST

lnorby_media_upload_image:
    path: /upload/image
    controller: Lnorby\MediaBundle\Controller\MediaController::uploadImage
    methods: POST

lnorby_media_download:
    path: /{path<.+>}
    controller: Lnorby\MediaBundle\Controller\MediaController::download
    methods: GET
